name: Send PR Data to Google Sheets

on:
  pull_request:
    types: [closed]

jobs:
  send-data:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Payload
        env:
          WEBHOOK_URL: ${{ secrets.GOOGLE_APPS_SCRIPT_WEBHOOK }}
          SECRET: ${{ secrets.WEBHOOK_SECRET }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          AUTHOR_URL: ${{ github.event.pull_request.user.html_url }}
          LABELS_JSON: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          EMAIL=""

          cat <<EOF > payload.json
          {
            "contributor_name": "${AUTHOR}",
            "contributor_email": "${EMAIL}",
            "github_link": "${AUTHOR_URL}",
            "labels": ${LABELS_JSON},
            "secret": "${SECRET}"
          }
          EOF

          echo "=== Sending Payload ==="
          cat payload.json | jq .

          curl -s -X POST \
            -H "Content-Type: application/json" \
            -d @payload.json \
            "$WEBHOOK_URL"
